# Generated by Django 3.0.2 on 2020-03-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq1', '0003_quiz_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
